[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	let g:quickrun_config = {
		\ '_': {
	 	\ 'runner': 'vimproc',
			\ 'runner/vimproc/updatetime': 40,
			\ 'outputter': 'error',
			\ 'outputter/error/success': 'quickfix',
			\ 'outputter/error/error': 'quickfix',
			\ 'outputter/buffer/split' : ':botright 10sp'
		\}
	\}

	let g:quickrun_no_default_key_mappings = 1
	nmap ! :cclose<CR>:write<CR>:QuickRun -mode n<CR>

'''
