[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'YorickPeterse/happy_hacking.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
	let g:everforest_background = 'soft'
'''

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
	let g:edge_style = 'neon'
'''

[[plugins]]
repo = 'fxn/vim-monochrome'

[[plugins]]
repo = 'cocopon/iceberg.vim'
