[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
	require'nvim-treesitter.configs'.setup {
	ensure_installed = 'all',
		highlight = {
		enable = true,
		disable = {},
		},
		ensure_installed = 'all',
	}
EOF
'''
