
[[plugins]]
repo = 'mfussenegger/nvim-jdtls'
hook_add = '''
	if has('nvim-0.5')
		augroup lsp
			au!
			au FileType java lua require('jdtls').start_or_attach({cmd = {'/root/.vim/jdt-ls.sh'}})
		augroup  end
	endif
'''
