[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
	let g:UltiSnipsEnableSnipMate = 0
	let g:UltiSnipsSnippetDirectories=["UltiSnips", "user_snippets"]

	"let g:UltiSnipsExpandTrigger = '<c-l>'
	"let g:UltiSnipsJumpForwardTrigger = '<c-j>'
	"let g:UltiSnipsJumpBackwardTrigger = '<c-k>'

	command! SNIP UltiSnipEdit
'''
