[[plugins]]
repo = 'vim-test/vim-test'
lazy = 1
hook_add = '''

	let g:test#strategy = {
		\ 'nearest' : 'neovim',
		\ 'file' : 'neovim',
		\ 'suite' : 'neovim',
		\}

	let g:test#preserve_screen = 1


	nmap <silent> t<C-n> :TestNearest<CR>
	nmap <silent> t<C-f> :TestFile<CR>
	nmap <silent> t<C-s> :TestSuite<CR>
	nmap <silent> t<C-l> :TestLast<CR>
	nmap <silent> t<C-g> :TestVisit<CR>}
'''
